version: '3.4'

services:
  api:
    working_dir: /app
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run migrations && npm run start"
    environment:
      NODE_ENV: development
      PORT: 8080
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
      DATABASE_HOST: db
      DATABASE_USER: dev
      DATABASE_NAME: dev
      DATABASE_PASSWORD: dev
      DATABASE_PORT: 5432
    networks:
      - internal
    depends_on:
      - db
  db:
    image: postgres:13.1
    ports:
      - 7000:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=2000'
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
